# Generated by Django 3.1 on 2021-03-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.FileField(upload_to='')),
                ('py_version', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('API_URL', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MLProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.machine')),
                ('ip_address', models.CharField(blank=True, max_length=15)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('RSA_KEY', models.CharField(blank=True, max_length=1024)),
                ('ssh_user', models.CharField(blank=True, max_length=64)),
            ],
            bases=('core.machine',),
        ),
        migrations.CreateModel(
            name='SparkMaster',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.machine')),
                ('SPARK_URL', models.CharField(blank=True, max_length=126)),
            ],
            bases=('core.machine',),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.mlproject'),
        ),
        migrations.AddField(
            model_name='environment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.machine'),
        ),
    ]
