# Generated by Django 3.1 on 2021-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210315_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('froml', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
