# Generated by Django 3.1 on 2021-04-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210323_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='message',
            new_name='template',
        ),
    ]
